import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import departmentsRouter from "./departments";
import doctorsRouter from "./doctors";
import appointmentsRouter from "./appointments";
import assistantsRouter from "./assistants";
import queueRouter from "./queue";
import prescriptionsRouter from "./prescriptions";
import medicinesRouter from "./medicines";
import subscriptionsRouter from "./subscriptions";
import bannersRouter from "./banners";
import adminRouter from "./admin";
import countriesRouter from "./countries";
import noticesRouter from "./notices";
import friendsRouter from "./friends";
import chatRouter from "./chat";
import notificationsRouter from "./notifications";
import reviewsRouter from "./reviews";
import emailSettingsRouter from "./email-settings";
import availabilityRouter from "./availability";
import shopRouter from "./shop";
import rxTemplatesRouter from "./rx-templates";
import rxSettingsRouter from "./rx-settings";
import appSettingsRouter from "./app-settings";
import blogRouter from "./blog";
import menuItemsRouter from "./menu-items";
import storageRouter from "./storage";
import advertisementsRouter from "./advertisements";
import adminSettingsRouter from "./admin-settings";
import adsenseSlotsRouter from "./adsense-slots";
import auditLogsRouter from "./audit-logs";
import migrationsRouter from "./migrations";
import calculatorsRouter from "./calculators";
import patientRouter from "./patient";
import queueDisplayDevicesRouter from "./queue-display-devices";
import slidersRouter from "./sliders";
import toolsRouter from "./tools";
import paymentGatewaysRouter from "./payment-gateways";
import paymentCheckoutRouter from "./payment-checkout";
import paymentCheckoutShurjopayRouter from "./payment-checkout-shurjopay";
import paymentCheckoutAamarpayRouter from "./payment-checkout-aamarpay";
import emergencyContactsRouter from "./emergency-contacts";
import bloodDonorsRouter from "./blood-donors";
import networkRouter from "./network";
import videoPromotionsRouter from "./video-promotions";
import pricingRouter from "./pricing";
import assistantApiRouter from "./assistant-api";
import displayRouter from "./display";
import adminDisplayRouter from "./admin-display";
import ambulanceRouter from "./ambulance";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(departmentsRouter);
router.use(doctorsRouter);
router.use(appointmentsRouter);
router.use(assistantsRouter);
router.use(queueRouter);
router.use(prescriptionsRouter);
router.use(medicinesRouter);
router.use(subscriptionsRouter);
router.use(bannersRouter);
router.use(adminRouter);
router.use(countriesRouter);
router.use(noticesRouter);
router.use(friendsRouter);
router.use(chatRouter);
router.use(notificationsRouter);
router.use(reviewsRouter);
router.use(emailSettingsRouter);
router.use(availabilityRouter);
router.use(shopRouter);
router.use(rxTemplatesRouter);
router.use(rxSettingsRouter);
router.use(appSettingsRouter);
router.use(blogRouter);
router.use(menuItemsRouter);
router.use(storageRouter);
router.use(advertisementsRouter);
router.use(adminSettingsRouter);
router.use(adsenseSlotsRouter);
router.use(auditLogsRouter);
router.use(migrationsRouter);
router.use(calculatorsRouter);
router.use(patientRouter);
router.use(queueDisplayDevicesRouter);
router.use(slidersRouter);
router.use(toolsRouter);
router.use(paymentGatewaysRouter);
router.use(paymentCheckoutRouter);
router.use(paymentCheckoutShurjopayRouter);
router.use(paymentCheckoutAamarpayRouter);
router.use(emergencyContactsRouter);
router.use(bloodDonorsRouter);
router.use(networkRouter);
router.use(videoPromotionsRouter);
router.use(pricingRouter);
router.use(assistantApiRouter);
router.use(displayRouter);
router.use(adminDisplayRouter);
router.use(ambulanceRouter);

export default router;
